### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by mitya33**

### CODE REVIEW

**Comment by amadeus711** [comment]
image
Please use `git rebase` to ensure the purity of PR.

**Comment by 07akioni** [comment]
Please rebase your commits.

**Comment by mitya33** [comment]
In truth I'm not sure what you mean. I just clicked the "Edit this page on Github" link and edited the content. Unfortunately I'm not a GH whizz; could you possibly elaborate, so I can contribute?

**Comment by 07akioni** [comment]
added in 77fce929dbb14bf98ab11a9c6bc3e49976a75ada

**Pull request closed without merging**
