### PR TITLE
fix(tree): 修复children空数组会渲染箭头

### PR DESCRIPTION
**Pull request by k983551019**
修复children空数组会渲染箭头

### CODE REVIEW

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/commit/73eade2a26c1bdef236a570393d3e36c4ce6a42c

**Comment by k983551019** [comment]
> #4176
> 
> [73eade2](https://github.com/tusen-ai/naive-ui/commit/73eade2a26c1bdef236a570393d3e36c4ce6a42c)
> 
> 有解决方案了

文档貌似没写

> #4176
> 
> [73eade2](https://github.com/tusen-ai/naive-ui/commit/73eade2a26c1bdef236a570393d3e36c4ce6a42c)
> 
> 有解决方案了

ignore-empty-children 变为了 get-children  被去掉了？

**Comment by jahnli** [comment]
ignore-empty-children 变为了 get-children

**Comment by k983551019** [comment]
> ignore-empty-children 变为了 get-children

解决了 试出来
image
看文档有点懵

**Pull request closed without merging**
