### PR TITLE
docs(dialog): fix transform-origin prop desc

### LINKED ISSUE #3901: Add the option to set transform-origin for dialogs
### This function solves the problem (这个功能解决的问题)
I see there is an option to add :transform-origin="'center'" for simple modals, but seems there is no such thing for dialogs, or maybe I can not find it!

Would i be possible to add it as well, so we can have the same behavor for dialogs as well in wanted?
### Expected API (期望的 API)
Add a new prop to set the :transform-origin="'center'" for dialogs

### PR DESCRIPTION
**Pull request by jizai1125**
closes #3901

### CODE REVIEW

**Review by amadeus711 — CHANGES_REQUESTED** [review]
This API has not been implemented yet. If you want to implement it, add documents in the implemented PR.

**Comment by jizai1125** [comment]
> This API has not been implemented yet. If you want to implement it, add documents in the implemented PR.

dialog 内部不是用的 modal 么，modal 实现了，dialog 不就可以用了么？

**Comment by amadeus711** [comment]
> > This API has not been implemented yet. If you want to implement it, add documents in the implemented PR.
> 
> dialog 内部不是用的 modal 么，modal 实现了，dialog 不就可以用了么？

image
dialog 实现时有用到 modal，但是 transform-origin 并没有透传到 modal，需要处理一下

**Comment by amadeus711** [comment]
> 

我截图的地方需要 dialog 把参数传到 modal 里，我有时间处理一下吧

**Pull request closed without merging**
