### PR TITLE
feat: For the NTree Update callback function, provide the row information

### LINKED ISSUE #3885: Tree update:checked-row-keys，无法获取到当前行信息
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance steps (重现步骤)
单独对数据行操作需要对大量的数据进行处理，无法捕获用户操作具体数据行

### Expected results (期望的结果)
update:checked-row-keys，提供第三个参数为当前行信息

### Actual results (实际的结果)
单独对数据行操作需要对大量的数据进行处理，无法捕获用户操作具体数据行

### PR DESCRIPTION
**Pull request by jahnli**
For the NTree Update callback function, provide the row information

on-update:checked-keys( rowData:RawNode,keys: Array<string | number>, option: Array<TreeOption | null>) )
on-update:indeterminate-keys( rowData:RawNode,keys: Array<string | number>, option: Array<TreeOption | null>) )
on-update:expanded-keys( rowData:RawNode,keys: Array<string | number>, option: Array<TreeOption | null>) )
on-update:selected-keys( rowData:RawNode,keys: Array<string | number>, option: Array<TreeOption | null>) )

close #3885

### CODE REVIEW

**Comment by jahnli** [comment]
close https://github.com/tusen-ai/naive-ui/issues/3885

**Comment by amadeus711** [comment]
The `rawData` is the newly added param, to ensure compatibility, it should be the last param.

**Comment by amadeus711** [comment]
And please add changelog, this is 'feat' pr.

**Comment by jahnli** [comment]
OK, I will change rowData to the third parameter later,

**Comment by jahnli** [comment]
@amadeus711  modification completed

**Comment by 07akioni** [comment]
image

把第三个参数处理一下，把行为和节点数据放在一个对象里

**Comment by jahnli** [comment]
@07akioni  completed

**Pull request closed without merging**
