### PR TITLE
docs(nuxt): `defineNuxtConfig` is auto imported

### PR DESCRIPTION
**Pull request by cinob**

### CODE REVIEW

**Comment by Sepush** [comment]
Will Nuxt auto import this by default? if not we should not remove this

**Comment by 07akioni** [comment]
It's also for IDE type inference.

**Comment by cinob** [comment]
`defineNuxtConfig` is deprecated. Remove import or alternatively use import { defineNuxtConfig } from 'nuxt/config'
[v3.0.0-rc.10](https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.10)

**Comment by cinob** [comment]
The `defineNuxtConfig` api has been removed in rc14 [#9029](https://github.com/nuxt/framework/pull/9029)
@07akioni

**Pull request closed without merging**
