### PR TITLE
fix(base-loading): revert to the old code & make animation work with blocking method & fix fur in animation

### LINKED ISSUE #3556: 加载Spin组件 圆圈动画有毛刺感
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 104.0.5112.81

### System and its version (系统及其版本)
Win 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/spin

### Reappearance steps (重现步骤)
使用加载 Spin组件

### Expected results (期望的结果)
——

### Actual results (实际的结果)
Spin的圆圈感觉不平滑，有很多凸起的像素，给人造成毛刺感

### Remarks (补充说明)
loading gif

仔细看也能发现 时不时有个灰色小像素块在圆圈轨迹上出现

### PR DESCRIPTION
**Pull request by suica**
closes #3556

### CODE REVIEW

**Comment by Sepush** [comment]
may add a demo for js blocking case like this one https://codesandbox.io/s/currying-hooks-ef7g87?file=/src/App.vue

**Comment by suica** [comment]
This is because I wrapped the svg with a rotating container, which has a longer period than the spinner itsself.
It turns out we cannot use svg animation and css animation together and expect them to have the same phase. Svg animation will be blocked by JS, but simple css animation will not.
So we need to replace all svg animation with css animation. Is there any way to construct css animation in `tsx` file?

**Comment by 07akioni** [comment]
> This is because I wrapped the svg with a rotating container, which has a longer period than the spinner itsself. It turns out we cannot use svg animation and css animation together and expect them to have the same phase. Svg animation will be blocked by JS, but simple css animation will not. So we need to replace all svg animation with css animation. Is there any way to construct css animation in `tsx` file?

Using `css-render`

**Comment by 07akioni** [comment]
> not blocking but animation get slow,Is this acceptable？cc @07akioni
> 
>  [  ](https://private-user-images.githubusercontent.com/39197136/253963075-173a70c7-cb69-4f6e-a575-aa0fc5f3d100.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTk3ODMsIm5iZiI6MTcwMzA5OTQ4MywicGF0aCI6Ii8zOTE5NzEzNi8yNTM5NjMwNzUtMTczYTcwYzctY2I2OS00ZjZlLWE1NzUtYWEwZmM1ZjNkMTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTY0N2E4M2ZjNjk5ZjhlYjBlYmM3ZTY2ZDU0MDgzNTYxZWE4OWJlYzE5YWI4ZTM3ODk2MmFiOTYwYWNlYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZYYeqv3md1LvbGdHwnpOu0c0uhBlk9IBkqcwQIGowI) [ ](https://private-user-images.githubusercontent.com/39197136/253963075-173a70c7-cb69-4f6e-a575-aa0fc5f3d100.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTk3ODMsIm5iZiI6MTcwMzA5OTQ4MywicGF0aCI6Ii8zOTE5NzEzNi8yNTM5NjMwNzUtMTczYTcwYzctY2I2OS00ZjZlLWE1NzUtYWEwZmM1ZjNkMTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTY0N2E4M2ZjNjk5ZjhlYjBlYmM3ZTY2ZDU0MDgzNTYxZWE4OWJlYzE5YWI4ZTM3ODk2MmFiOTYwYWNlYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZYYeqv3md1LvbGdHwnpOu0c0uhBlk9IBkqcwQIGowI)

It used to be this.

**Pull request merged**
