### PR TITLE
feat(n-image): add `render-toolbar` prop

### PR DESCRIPTION
**Pull request by jahnli**
close https://github.com/tusen-ai/naive-ui/issues/5673
close https://github.com/tusen-ai/naive-ui/issues/5665
close https://github.com/tusen-ai/naive-ui/issues/5632

### CODE REVIEW

**Comment by jahnli** [comment]
OK了

**Comment by Sarkhad** [comment]
Any progress on the merge?

**Comment by daomiaru** [comment]
你好。请问自定义工具栏的这个功能已经好了吗？希望能有个配置可以配置是否需要的工具栏按钮

**Comment by jahnli** [comment]
> Any progress on the merge?

Function ready, waiting for merge

**Pull request merged**
